# ignite: diffusion-ignite

# log_interval: 1
# score_name: loss
use_checkpoint: true
use_early_stopping: false
use_lr_scheduler: false
use_multi_gpu: false

metrics:
  # FID:
  SSIM:
    data_range: 1.0

checkpoint:
  _target_: ignite.handlers.checkpoint.Checkpoint
  save_handler: artifacts/checkpoints/
  filename_prefix: best
  n_saved: 10
  # require_empty: false

early_stopping:
  _target_: ignite.handlers.early_stopping.EarlyStopping
  patience: 5

lr_scheduler:
