name: rtk
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - ipywidgets
  - jupyter_core
  - pip
  - pip:
      - opencv-python
      - pytest
      - rich-cli
      - -r requirements.txt
