# transforms: diffusion-transforms

load:
  - _target_: monai.transforms.LoadImaged
    keys: [image]
    image_only: true
  - _target_: monai.transforms.EnsureChannelFirstd
    keys: [image]
  - _target_: monai.transforms.ScaleIntensityd
    keys: [image]
  # - _target_: monai.transforms.EnsureType
  #   dtype: [image]

train:
  - _target_: monai.transforms.RandAffined
    keys: [image]
    padding_mode: zeros
    prob: 0.5
    scale_range: [[-0.05, 0.05], [-0.05, 0.05]]
    spatial_size: [64, 64]
    translate_range: [[-1, 1], [-1, 1]]
