# models: diffusion-unet-model

defaults:
  - _self_

# https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_ddpm/2d_ddpm_tutorial_ignite.ipynb
model:
  # cross_attention_dim: 1
  # with_conditioning: true
  _target_: generative.networks.nets.DiffusionModelUNet
  attention_levels: [false, false, true]
  in_channels: 3
  num_channels: [64, 64, 64]
  num_head_channels: [0, 0, 64]
  num_res_blocks: 1
  out_channels: 3
  spatial_dims: 2

criterion:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.Adam
  lr: 2.5e-5

scheduler:
  _target_: generative.networks.schedulers.DDPMScheduler
  beta_end: 0.0195
  beta_start: 0.0005
  num_train_timesteps: 1000
  schedule: "scaled_linear_beta"

inference:
  _target_: generative.inferers.DiffusionInferer
