# models: default-model

defaults:
  - _self_
  - criterion: cross-entropy
  - optimizer: adam

model:
  _target_: timm.create_model
  model_name: maxvit_rmlp_base_rw_384.sw_in12k_ft_in1k
  num_classes: 2
  pretrained: ${job.use_pretrained_weights}
