# models: densenet-model

defaults:
  - _self_

model:
  _target_: monai.networks.nets.DenseNet121
  in_channels: 1
  out_channels: 2
  spatial_dims: 3

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 5e-5
