# models: diffusion-unet-model

defaults:
  - _self_

model:
  _target_: generative.networks.nets.DiffusionModelUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  num_channels: [256, 256, 512]
  attention_levels: [false, false, true]
  num_head_channels: [0, 0, 512]
  num_res_blocks: 2

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 5e-5

scheduler:
  _target_: generative.networks.schedulers.DDPMScheduler
  beta_start: 0.0005
  beta_end: 0.0195
  num_train_timesteps: 1000
  schedule: "scaled_linear_beta"

inference:
  _target_: generative.inferers.DiffusionInferer
