# models: inception-model

defaults:
  - _self_
  - criterion: cross-entropy
  - optimizer: sgd

model:
  _target_: timm.create_model
  model_name: inception_v3
  num_classes: 2
  pretrained: ${job.use_pretrained}
