# models: mobilenet-model

defaults:
  - _self_
  - criterion: cross-entropy
  - optimizer: sgd

model:
  _target_: timm.create_model
  model_name: mobilenetv2_100
  num_classes: 2
  pretrained: ${job.use_pretrained}
