# models: resnet-model

defaults:
  - _self_
  - criterion: cross-entropy
  - optimizer: sgd

model:
  _target_: timm.create_model
  model_name: resnet18
  num_classes: 2
  pretrained: ${job.use_pretrained_weights}
