# models: vit-model

defaults:
  - _self_
  - criterion: cross-entropy
  - optimizer: adam

model:
  _target_: timm.create_model
  model_name: vit_base_patch16_clip_384
  num_classes: 2
  pretrained: ${job.use_pretrained}

load_model:
  name: vit_base_patch16_clip_384_PEDIATRICS_CHESTXRAY14
  version: 1
