# torchmetrics: diffusion

metrics:
  - _target_: torchmetrics.image.StructuralSimilarityIndexMeasure
  - _target_: torchmetrics.image.fid.FrechetInceptionDistance
    normalize: false
  - _target_: torchmetrics.image.inception.InceptionScore
    normalize: false

remap:
  FrechetInceptionDistance: fid
  InceptionScore: inception
  MultiScaleStructuralSimilarityIndexMeasure: ms-ssim
  StructuralSimilarityIndexMeasure: ssim