# preprocessing: default-preprocessing

# sample_to_value: -1
use_sampling: false
sampling_method:
  sample_to_value: -1
  method:
    _target_: imblearn.datasets.make_imbalance
# subset: [0]
# use_subset: true
