# * python scripts/run_train.py --config-dir=$(pwd)/configs/ --config-name=chest-xray-experiments

# Sampling modes
# python scripts/run_train.py --config-dir=$(pwd)/configs/ --config-name=chest-xray-experiments -m
# * job.use_pretrained=true,false datasets.preprocessing.use_sampling=false job.device=0
# * job.use_pretrained=true,false datasets.preprocessing.use_sampling=true datasets.preprocessing.sample_to_value=3500 job.device=1
# * job.use_pretrained=true,false datasets.preprocessing.use_sampling=true datasets.preprocessing.sample_to_value=5000 job.device=2

defaults:
  - _self_
  - datasets: chest-xray-dataset
  - job: run-train
  - models: vit-model
  # module configurations
  - ignite: ignite
  - mlflow: local
  - sklearn: classifier
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
postfix: ""
timestamp: ${now:%H-%M-%S}

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
