# python scripts/run_train.py --config-dir=$(pwd)/configs/ --config-name=chest-xray-baseline

defaults:
  - _self_
  - datasets: chest-xray
  - ignite: ignite
  - models: densenet-model
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
timestamp: ${now:%H-%M-%S}

job:
  device: 0
  dry_run: false
  epoch_length: null
  max_epochs: 25
  perform_validation: true
  random_state: 42
  set_track_meta: false
  use_autocast: true
  use_azureml: true
  use_mlflow: true
  use_pretrained_weights: true
  use_transforms: true
  train_test_split:
    random_state: ${job.random_state}
    shuffle: true
    test_size: 0.1

mlflow:
  experiment_name: chest-xray-baseline
  tracking_uri: file:///home/nicoleg/workspaces/teddytoolkit/mlruns/

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
