# --config-dir=$(pwd)/configs/ --config-name=tests

defaults:
  - _self_
  - datasets: chest-xray
  - ignite: ignite
  # - models: diffusion-unet-model
  - models: densenet-model
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
timestamp: ${now:%H-%M-%S}
# index: IXI_ID
# target: "SEX_ID (1=m, 2=f)"

job:
  device: 0
  dry_run: true
  epochs: 10
  perform_validation: true
  random_state: 42
  set_track_meta: false
  use_autocast: true
  use_azureml: false
  use_mlflow: false
  use_pretrained_weights: true
  use_transforms: false
  train_test_split:
    random_state: ${job.random_state}
    shuffle: true
    test_size: 0.1

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
