# --config-dir=$(pwd)/configs/ --config-name=tests

defaults:
  - _self_
  - datasets: ixi
  - ignite: ignite
  - models: diffusion-unet-model
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
timestamp: ${now:%H-%M-%S}
index: IXI_ID
target: "SEX_ID (1=m, 2=f)"

job:
  debug: true
  device: 3
  dry_run: true
  random_state: 42
  set_track_meta: false
  use_azureml: false
  use_mlflow: false
  use_pretrained_weights: true
  use_transforms: false
  train_test_split:
    test_size: 0.1
    random_state: ${job.random_state}
    shuffle: true

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
