defaults:
  - _self_
  - dataset: ixi
  - ignite: ignite
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
timestamp: ${now:%H-%M-%S}
index: IXI_ID
target: "SEX_ID (1=m, 2=f)"

job:
  debug: true
  dry_run: true
  random_state: 42
  use_azureml: false
  use_mlflow: false

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
