# * rtk-job --config-dir=$(pwd)/configs/ --config-name=tests

defaults:
  - _self_
  - datasets: chest-xray14-dataset
  - job: train-diffusion
  - models: ddpm-model
  # module configurations
  - ignite: diffusion-ignite
  - mlflow: local
  - sklearn: classifier
  # overrides:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

date: ${now:%Y-%m-%d}
postfix: "test"
timestamp: ${now:%H-%M-%S}

# hydra settings
hydra:
  job:
    chdir: true
  searchpath:
    - file:///home/nicoleg/workspaces/dissertation/configs
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
