defaults:
  - _self_
  - models: siglip
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

env_file: /data/nicoleg/workspaces/dissertation/.env
name: tests
dry_run: true
push_to_hub: false
date: ${now:%Y-%m-%d}
timestamp: ${now:%H-%M-%S}
dataset_id:
data_dir: /data/nicoleg/datasets/physionet.org/files/mimic-cxr-jpg/2.1.0
batched: false
batch_size: 1
positive_class: Pneumonia
with_rank: false

hydra:
  job:
    chdir: true
  sweep:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
    subdir: ${hydra.job.override_dirname}
  run:
    dir: outputs/${hydra.job.config_name}/${date}/${timestamp}
