# datasets: chest-xray14-dataset

defaults:
  - _self_
  # - preprocessing: default-preprocessing
  - transforms: default-transforms

dim: 229
extension: .png
index: "Image Index"
labels: ["No Finding", "Pneumonia"]
target: "Finding Labels"
patient_data: /home/nicoleg/workspaces/teddytoolkit/.data/Chest_XRay_14_Kaggle_RGB/Data_Entry_2017.csv
scan_data: /home/nicoleg/workspaces/teddytoolkit/.data/Chest_XRay_14_Kaggle_RGB/
encoding:
  "No Finding": 0
  "Pneumonia": 1

instantiate:
  _target_: monai.data.ImageDataset

dataloader:
  _target_: monai.data.ThreadDataLoader
  batch_size: 16
  num_workers: 24

preprocessing:
  subset: ["Atelectasis", "Edema", "Effusion", "Consolidation", "Pneumonia"]
  use_sampling: true
  sampling_method:
    sample_to_value: 5000
    method:
      _partial_: true
      _target_: imblearn.datasets.make_imbalance
      verbose: true
# additional_datasets:
#   dataset_configs:
#     - filepath: /home/nicoleg/workspaces/teddytoolkit/configs/datasets/chest-xray-dataset.yaml
#       loader: load_chest_xray_dataset
