# datasets: chest-xray-dataset

defaults:
  - _self_
  - preprocessing: default-preprocessing
  - transforms: default-transforms

dim: 229
extension: .jpeg
labels: [NORMAL, PNEUMONIA]
patient_data: null
scan_data: /home/nicoleg/workspaces/teddytoolkit/.data/Chest_XRay_Images_RGB/
encoding:
  0: NORMAL
  1: PNEUMONIA

instantiate:
  _target_: monai.data.ImageDataset

dataloader:
  _target_: monai.data.ThreadDataLoader
  batch_size: 16
  num_workers: 24
