# datasets: chest-xray

defaults:
  - _self_

extension: .jpeg
patient_data: null
# scan_data: /home/nicoleg/workspaces/teddytoolkit/ttk/.cache/datasets/scans/Chest_XRay_Images:latest/
scan_data: /home/nicoleg/workspaces/teddytoolkit/.data/Chest_XRay_Images_RGB/
labels: [NORMAL, PNEUMONIA]

instantiate:
  _target_: monai.data.ImageDataset

dataloader:
  _target_: monai.data.ThreadDataLoader
  batch_size: 16
  num_workers: 24
  # non_blocking: true
  # use_thread_workers: true

transforms:
  load:
    - _target_: monai.transforms.ScaleIntensity

    - _target_: monai.transforms.EnsureChannelFirst
      # channel_dim: no_channel

    - _target_: monai.transforms.EnsureType
      track_meta: true

    - _target_: monai.transforms.Resize
      spatial_size: [224, 224]

    # - _target_: monai.transforms.Transpose
    #   # indices: [2, 0, 1]
    #   indices: [0, 3, 1, 2]

  train:
    - _target_: monai.transforms.RandFlip
      prob: 0.5

    - _target_: monai.transforms.RandRotate90
      prob: 0.5

    - _target_: monai.transforms.RandAdjustContrast
      gamma: [1.0, 2]
      prob: 0.5
