# job: run-eval

device: 1
dry_run: true
epoch_length: null
max_epochs: 1
mode: evaluate
perform_validation: true
random_state: 101
set_track_meta: true
use_autocast: true
use_azureml: true
use_mlflow: true
use_pretrained: true
use_transforms: false

# function kwargs
train_test_split:
  shuffle: true
  test_size: 0.1
prepare_function:
  _target_: rtk.ignite.prepare_run
