# job: test-run

device: 2
dry_run: true
epoch_length: null
max_epochs: 10
perform_validation: true
random_state: 42
set_track_meta: false
use_autocast: true
use_azureml: true
use_mlflow: true
use_pretrained_weights: true
use_transforms: true

# function kwargs
train_test_split:
  shuffle: true
  test_size: 0.1
prepare_function:
  _target_: ttk.ignite.prepare_run
