# job: test-run

device: 3
dry_run: true
epoch_length: 32
max_epochs: 3
perform_validation: true
random_state: 42
set_track_meta: false
use_autocast: true
use_azureml: false
use_mlflow: false
use_pretrained_weights: true
use_transforms: true

# function kwargs
train_test_split:
  shuffle: true
  test_size: 0.1
prepare_function:
  _target_: ttk.ignite.prepare_run
