# job: train-diffusion

device: 0
dry_run: true
epoch_length: 64
max_epochs: 3
perform_validation: true
random_state: 42
set_track_meta: false
use_autocast: true
use_azureml: false
use_mlflow: true
use_pretrained_weights: true
use_transforms: true

# function kwargs
train_test_split:
  shuffle: true
  test_size: 0.1
prepare_function:
  _target_: rtk.ignite.prepare_diffusion_run
